### PR TITLE
feat: stop guachafita

### LINKED ISSUE #8: ✨ [Feature Request]: Add "conventional commit" rules with husky
Add things because Lana no deja de joder

### Resources
- [Conventional Commits docs](https://www.conventionalcommits.org/en/v1.0.0/)
- [Wiki page](https://github.com/Lana-Software/una-red/wiki/%E2%98%91-Conventional-Commits) by @Kolozuz, with a brief introduction and guide to start using these conventions

### PR DESCRIPTION
**Pull request by JohnGolgota**
# Change Details 

Try use this shit local, to see if this is aceptable, no se

debería impedir commits sin la convention y no estoy seguro de como documentar el modo de uso, no sé qué necesite instalar

## Before merging branches 

- [x] Reviewed by one or more developers on the team.
- [x] Tests.
- [x] Documentation (the structure that we will be using from now on). (done [here](https://github.com/Lana-Software/una-red/wiki/%E2%98%91-Conventional-Commits))

### CODE REVIEW

**Comment by JohnGolgota** [comment]
1. install new devDep

**Comment by Kolozuz** [comment]
Tested the changes and documented the implementation details over here: 
- [Conventional Commits Wiki page](https://github.com/Lana-Software/una-red/wiki/%E2%98%91-Conventional-Commits) _by @Kolozuz_ (brief introduction and guide to start using these conventions)

Reviewing, accepting and marking as closed...

**Review by Kolozuz — COMMENTED** [review]
seems good

**Comment by JohnGolgota** [comment]
2. Run pnpm prepare

**Pull request merged**
